#!/bin/bash
#iMobileDevice Framework GPS Spoofer
#By: Joel Horensma
#
#
clear
trap ctrl_c INT
##########
#FUNCTIONS
##########
source Functions/functions.sh
checkRequirements
checkDeviceConnection
API_KEY=$(cat API_Key/API_Key.txt)


#####
#MENU
#####
DEVICE_LOCATION="Real Location"
function menu() {
clear
checkDeviceConnection
printf "GPS Spoofer \n"
printf "By: Joel Horensma \n\n"
printf "UDID: ${DEVICE_UDID} \n"
printf "Device type: ${DEVICE_TYPE} \n"
printf "Device OS version: ${DEVICE_OS_VERSION} \n"
printf "Device GPS Location: ${DEVICE_LOCATION} \n\n"
options=("Choose Location" "Reset GPS" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Choose Location")
        clear
        checkDeviceConnection
        checkDeveloperDiskImageMounted
        setDeviceLocation
        idevicesetlocation -u ${DEVICE_UDID} -- ${LAT} ${LONG}
        printf "\nDevice location set to: ${DEVICE_LOCATION} \n\n"
        read -p "Press [Enter]: "
        menu
        ;;
        "Reset GPS")
        clear
        checkDeviceConnection
        checkDeveloperDiskImageMounted
        idevicesetlocation -u $DEVICE_UDID reset
        DEVICE_LOCATION="Real Location"
        printf "Device GPS co-ordinates were reset. \n\n"
        read -p "Press [Enter]: "
        menu
        ;;
        "Quit")
        ctrl_c
        ;;
             *)
        echo "Invalid option ${REPLY}"
        ;;
    esac
done
}
menu
